#!/bin/sh

set -e

#host=$(env | grep _TCP_ADDR | cut -d = -f 2 | sort -n | head -1)
#port=$(env | grep _TCP_PORT | cut -d = -f 2 | sort -n | head -1)

echo -n "waiting for TCP connection to $TARGET_IP:$TARGET_PORT..."

while ! nc -w 1 $TARGET_IP $TARGET_PORT 2>/dev/null
do
  echo -n .
  sleep 1
done

echo 'ok'
